### ISSUE TITLE
Use of asymetric keys?

### ISSUE THREAD

**Issue by tomkersten** [kaushalmeena/digi-cloak#1]
Neat project!

I am essentially illiterate in cryptography, so forgive me if this is an obvious question: **How difficult would it be to use a pub/private keypair for the encryption-portion of this?**

I provide a public key of someone. They can use their private key to decode it.

I realize this is essentially just using standard PGP keys, but, I like the stenography-aspect of this and was just curious.

**Comment by kaushalmeena** [comment]
Currently, this project is using the AES algorithm provided by the crypto-js (https://www.npmjs.com/package/crypto-js) library, also this library only has symmetric (single key pair) cryptography algorithms, for asymmetric (public/private key pair) encryption we can use https://www.npmjs.com/package/jsencrypt library which is based on RSA
